# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html

# Site
url: http://yoursite.com
site_type: mini # single, mini, big
title: Boilerplate Site Title
description:
year_started: 2013
email: # optional, used on terms, and privacy pages
author: # not currently used in template
root: / # If subdirectory, url: http://yoursite.com/child and root: /child/
disqus_shortname:
google_analytics:

# Menu
menu:
  Privacy Policy: /privacy/
  Terms of Use: /terms/
footerMenu:
  Privacy Policy: /privacy/
  Terms of Use: /terms/
  # Google+: 

# Big
permalink: :category/:title/
tag_dir: tags
category_dir: '' # for uncategorized only
rss:
archive: 0 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
category: 2 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
tag: 2 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
per_page: 10 # Set per_page to 0 to disable pagination
pagination_dir: page
default_category: uncategorized
category_map: # category slug
tag_map: # tag slug

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D YYYY
time_format: H:mm:ss

# Design
google_font: Open+Sans:400,700,400italic,700italic

css:
  - '/stylesheets/style.css'
headScripts:
  - '/scripts/responsive-nav.js'
scripts:
  - '//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'
  - '/scripts/fastclick.js'
  - '/scripts/fixed-responsive-nav.js'

# Writing
excerpt_link: Read More
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab

max_open_file: 100
multi_thread: true
filename_case: 1
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: boilerplate
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Hexo input and output folders
source_dir: source
public_dir: public

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  type: