# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html

# Site
url: http://yoursite.com
site_type: big # single, mini, big
title: Boilerplate Site Title
description: # SEO meta description for the site. Roughly 160 characters max.
year_started: 2014
email: # optional, used on terms, and privacy pages
disqus_shortname:
root: / # If subdirectory, url: http://yoursite.com/child and root: /child/
google_analytics:

# Main menu includes what you list here as name: /slug/ as well as any categories found in posts
menu:
  # Page Name: /page-name/

# Footer menu... you can leave privacy and terms
footerMenu:
  Privacy Policy: /privacy/
  Terms of Use: /terms/
  # Google+: 

# Google Font
google_font: Open+Sans:400,700,400italic,700italic

# Need to add more stylesheets or JS... add it here.
css:
  - '/stylesheets/style.css'
headScripts:
  - '//cdnjs.cloudflare.com/ajax/libs/responsive-nav.js/1.0.32/responsive-nav.min.js'
scripts:
  - '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js'
  - '//cdn.jsdelivr.net/fastclick/1.0.1/fastclick.min.js'
  - '//cdn.jsdelivr.net/jquery.mixitup/2.1.5/jquery.mixitup.min.js'
  - '/scripts/navigation.js'


#
# You should probably leave everything below here alone
#


# Big
permalink: :category/:title/
category_dir: '' # for uncategorized only
archive: 0 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
category: 1 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
tag: 0 # 2: Enable pagination, 1: Disable pagination, 0: Fully disable
tag_dir: tags
per_page: 10 # Set per_page to 0 to disable pagination
pagination_dir: page
default_category: uncategorized
category_map: # category slug
tag_map: # tag slug

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D YYYY
time_format: H:mm:ss

# Writing
excerpt_link: Read More
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab

# Misc or Not Used Hexo stuff
author: # not currently used in template
max_open_file: 100
multi_thread: true
filename_case: 1
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: boilerplate
exclude_generator:

# Markdown
## https://github.com/chjj/marked
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: false
  breaks: true
  smartLists: true
  smartypants: true
  xhtml: true # don't confuse html-truncate

highlight:
  enable: false
  line_number: false
  tab_replace:

# Hexo input and output folders
source_dir: source
public_dir: public

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

optimize:
  # Defaults
  image_min: true
  css_concat: true
  css_min: true
  js_concat: true
  js_min: true
  html_min: true
  gzip: true

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  type:
