menu:
  Home: /
  Blog: /blog
  About: /about
footerMenu:
  Privacy Policy: /privacy/
  Terms of Use: /terms/
  Contact: /contact/
  # Google+: 

excerpt_link: Read More

addthis:
  enable: false

fancybox: false

google_analytics:
rss:
google_font: Open+Sans:400,700,400italic,700italic